-- Generated by Noctalia

local primary = "rgb({{colors.primary.default.hex_stripped}})"
local surface = "rgb({{colors.surface.default.hex_stripped}})"
local on_surface = "rgb({{colors.on_surface.default.hex_stripped}})"
local on_surface_variant = "rgb({{colors.on_surface_variant.default.hex_stripped}})"
local secondary = "rgb({{colors.secondary.default.hex_stripped}})"
local error = "rgb({{colors.error.default.hex_stripped}})"
local shadow = "rgb({{colors.shadow.default.hex_stripped}})"

local function apply_theme()
    hl.config({
        general = {
            col = {
                active_border = primary,
                inactive_border = surface,
            },
        },
		decoration = {
			shadow = {
				color = shadow,
			},
			glow = {
				color = primary,
				color_inactive = surface,
			},
		},
        group = {
            col = {
                border_active = secondary,
                border_inactive = surface,
                border_locked_active = error,
                border_locked_inactive = surface,
            },

            groupbar = {
                col = {
                    active = secondary,
                    inactive = surface,
                    locked_active = error,
                    locked_inactive = surface,
                },
                text_color = on_surface,
                text_color_inactive = on_surface_variant,
            },
        },
    })
end

return {
    colors = {
        primary = primary,
        surface = surface,
        surface_variant = surface_variant,
        secondary = secondary,
        error = error,
        shadow = shadow,
    },
    apply_theme = apply_theme
}
